name: Get Feed Scheduled

on:
  schedule:
    - cron: "* * * * *"   # 1분 테스트
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "scheduler is alive"
